### ISSUE TITLE
Did you want to provide an address for NFT on certification?

### ISSUE THREAD

**Issue by thedarkjester** [manuelpires/blockchain-developer-bootcamp-final-project#1]
This is optional, but wanted to check..

Nice project -.. I like the `yes master` - nice touch.. was excpecting `yessss masssstterr`

**Comment by manuelpires** [comment]
Haha good one! 
Yes I added mi ENS domain in the README.md: `manuelpires.eth`
It is this address: 0xa592B977b98697eD0269B645Af1d09289faE8948

Thanks 😊

**Comment by thedarkjester** [comment]
aah cool- I missed that.. thanks
